export { default as Header } from "./header"
export { default as Hero } from "./hero"
export { default as Things } from "./ThingsToDo"
export { default as Follow } from "./Follow"
export { default as Footer } from "./Footer"
export { default as GalleryHeader } from "./Gallery"